### ISSUE TITLE
unstaging a highlighted section in an staged but untracked file does not work

### ISSUE THREAD

**Issue by alextes** [NeogitOrg/neogit#1362]
### Description

when staging a new file, i sometimes want to unstage part of that file. perhaps its not done, perhaps it belongs to a different feature / commit. highlighting the lines in the unstaged file and staging that way works fine. decent workaround, but you don't always notice ahead of time you've staged lines you don't want to commit (on a new file). 

trying to unstage yields the following error
```
error: patch failed: us-east-1/ansible/playbook.yaml:0
error: us-east-1/ansible/playbook.yaml: patch does not apply
```

Here's a screenshot that makes the situation visual:
![Screenshot 2024-06-06 at 14 02 42](https://github.com/NeogitOrg/neogit/assets/2011351/edf87afd-63b5-4c41-b54b-66ba33d93516)

unstaging the commented lines at the end of the file will yield the error above.

### Neovim version

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202

### Operating system and version

macOS 14.5

### Steps to reproduce

1. create an untracked file like below, stage it, then try to unstage the commented lines at the end
```
- name: Setup docker for all nodes
  hosts: beacon_nodes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - docker
  tags: docker

- name: Setup beacon nodes
  hosts: beacon_nodes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - beacon-node
  tags: beacon-node
#
# - name: Setup simulation nodes
#   hosts: simulation-nodes
#   become: yes
#   vars:
#     ansible_python_interpreter: /usr/bin/python3
#   roles:
#     - simulation-node
```

### Actual behavior

See description.

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```
